### ISSUE TITLE
Clothing objects bug(?)

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#101]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=141387

He said hes been losing clothing items overnight. He deleted them and tried to re-buy them all. Now he can't buy clothing objects regardless of him having none.

From personal experience I've never witnessed the loss of clothing objects. 
Btw, how many items are you meant to be able to buy? Because on the dev server I managed to buy ~65. (I could buy more)

**Comment by reemyrobby** [comment]
Using "/resetallholsters" might resolve the issue regarding the clothing object purchase limit.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: OutW0rldSent: Monday, February 27, 2017 1:33 PMTo: TommyB123/redcountyrp-bugsReply To: TommyB123/redcountyrp-bugsCc: SubscribedSubject: [TommyB123/redcountyrp-bugs] Clothing objects bug(?) (#101)https://redcountyrp.com/forum/viewtopic.php?f=1019&t=141387
He said hes been losing clothing items overnight. He deleted them and tried to re-buy them all. Now he can't buy clothing objects regardless of him having none.
From personal experience I've never witnessed the loss of clothing objects.
Btw, how many items are you meant to be able to buy? Because on the dev server I managed to buy ~65. (I could buy more)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TommyB123/redcountyrp-bugs","title":"TommyB123/redcountyrp-bugs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TommyB123/redcountyrp-bugs"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Clothing objects bug(?) (#101)"}],"action":{"name":"View Issue","url":"https://github.com/TommyB123/redcountyrp-bugs/issues/101"}}}

**Comment by OutW0rld** [comment]
I'll tell him to do that and see if it works. Meanwhile the other issues are still to be solved, yeap.

**Comment by TommyB123** [comment]
This user somehow managed to accumulate 106 vest objects which have saved to his account. Probably due to an old bug. He can fix it by using /resetvest.

**Comment by TommyB123** [comment]
Not really a bug anymore.
