### ISSUE TITLE
[HIGH PRIORITY] Checkpoint system severely broken

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#191]
People have complained multiple times in /assistance that their checkpoints disappeared during the driving test. I looked into it, it was working pretty fine for me, but I think it is doing something with connection. Just like the bank's exiting issue.
Worth looking into all the tests, maybe just an optimization needed.

I need testing from someone, since I couldn't get the bug, but many people by now, got it on the live server.

**Comment by wtfrazr** [comment]
http://i.imgur.com/bmIKs7f.png

**Comment by reemyrobby** [comment]
Issue is still occurring. Raising the priority due to the inconvenience it causes.

**Comment by wtfrazr** [comment]
Why does this haven't been fixed yet? It's over 2 updates and still not a fix.

**Comment by TommyB123** [comment]
I put out a potential fix for it but didn't write it down on any changelogs in case it didn't work. I've yet to hear about the bug since but I could be wrong.

**Comment by wtfrazr** [comment]
I had an assistance yesterday that was about this. I told him to post a refund, maybe he did already.

**Comment by reemyrobby** [comment]
Can confirm it's still borked.

**Comment by reemyrobby** [comment]
Issue still persisting in Version 2.5.2. pls put more debugs

**Comment by reemyrobby** [comment]
Updated title to cover the whole checkpoint system.

**Comment by TommyB123** [comment]
the whole checkpoint system?? explain please???????

**Comment by reemyrobby** [comment]
The checkpoints have been an issue since Version 2.5, where a checkpoint would stay at Fort Carson Mall (which I assume has something to do with mall businesses). For every update, the issue is spreading throughout almost every feature that involves checkpoints - the driving test, fuel cap, side jobs, etc.

There must be something that is causing this, and several features (most are important) are affected because of this. Lead Administrators feel obliged to refund or manually issue licenses. Players cannot earn money because they cannot complete the side job. Administrators having to manually set fuel on a vehicle. We have to set this bug as high priority because it is affecting the gameplay experience of players rather severely.

To further elaborate; there are times when checkpoints would appear and get stuck even if you stand or drive past it. This forces players to fail the driving test or the side job. Relogging can SOMETIMES resolve the issue, but this should not be happening in the first place.

**Comment by wtfrazr** [comment]
There are like 4-5 daily assistances for disappeared checkpoints.

**Comment by wtfrazr** [comment]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=149487

**Comment by wtfrazr** [comment]
Still an issue with the driving license CPs, even after 2.5.2 R1.

**Comment by The-Kenth** [comment]
Has been fixed, I have tested out several features that revolve around the presence of checkpoints and so far I've had no issues with them.
