### ISSUE TITLE
'/drop' not functioning

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#2]
When you try to drop an item using the "/drop", it will return the "command not recognized" error. Possibly a side effect from the drop phone fix?

**Comment by TommyB123** [comment]
This is due to the array for dropped items only having 200 cells (or slots if you will)

That limit seems to have been reached on the main server and there isn't actually a fail-safe put in place to tell the user that limit has been reached. This has already been added for 2.3.5, but I didn't expect the limit to ever be reached. I guess that's what happens when the server is up for nearly three weeks without a restart.
