### ISSUE TITLE
Radio Stations Not Working

### ISSUE THREAD

**Issue by The-Kenth** [TommyB123/redcountyrp-bugs#200]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=146673

The following radio stations do not work:
Kickin' Country
Blues After House Radio
La Grosse Radio
Cheezy FM
HOT 108 JAMZ

**Comment by TommyB123** [comment]
I'd appreciate it if I could be supplied with working stream URLs.

**Comment by reemyrobby** [comment]
Kickin' Country _(I am not sure which Kickin' Country since there are several stations with the same name, though I used 181.FM's)_
http://www.181.fm/winamp.pls?station=181-kickincountry&file=181-kickincountry.pls

_Blues After House Radio - Seems that this station has already shut down_

La Grosse Radio
http://hd.lagrosseradio.info/lagrosseradio-metal-192.mp3

Cheezy FM
http://212.83.150.15:8253/stream.mp3

HOT 108 JAMZ
http://jbmedia-edge1.cdnstream.com:7080/hot108.m3u

**Comment by B1sh0p123** [comment]
Adding few more radio stations which don't work:
Metal > Idiobi Owl
Miscellaneous > Celiente 99
Rap > Nonstop Rap
(Can't find working URLs tho)

**Comment by The-Kenth** [comment]
Confirmed. Moved.
