### ISSUE TITLE
Vattachments disappear

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#279]
Freshly bought/duplicated vattachments are disappearing when the payday comes. They are still on in the dialog but they aren't shown on the car.

**Comment by wtfrazr** [comment]
Also I don't know if it was affected by the compulsion to use the /recovervehicle as I killed it in an accident but after that only the fifth object continued on with the strange anomaly, leaving the rest untouched as a payday came.

**Comment by TommyB123** [comment]
No, that would be unrelated. The cause of this bug was in the code I use to adjust object stream distance based on the size of their model. This loop did not exclude objects attached to vehicles, and there is a bug in the streamer plugin which causes objects attached to vehicles to disappear if any data related to them is manipulated. I've fixed this by preventing objects attached to cars from having their stream distance adjusted.
