### ISSUE TITLE
Inactive kick when not actually inactive

### ISSUE THREAD

**Issue by iamlarss** [TommyB123/redcountyrp-bugs#39]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=139091&p=1640733#p1639767

Not sure what the cause could be, maybe the ID? But I remember a bug report from a  few weeks ago with the same issue, happens very scarcely.

**Comment by TommyB123** [comment]
It seems this only happens when a player spawns right when the inactivity check happens. Reason being is because the player isn't spawned yet, their coordinates return to '0, 0, 0'. Since the array where a playerids position was last saved gets reset to '0, 0, 0', thus resulting in the player being kicked. This should be fixed now.
