### ISSUE TITLE
/find gives you the wrong location if inside an interior

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#65]
https://redcountyrp.com/forum/viewtopic.php?f=45&t=139110&p=1646703

Quoting original topic.

> Well I was patroling today when a guy called from the location of "Ocean Docks".
>
>We went to the cruiser there, so nobody so we decided to contact the caller.
The caller was situated inside the DMV, not at the Ocean Docks. It wasted us like 5 minutes to get there, then get back to DMV in Montgomery.

**Comment by DogNo** [comment]
There is one suggestion on the forums which if added will fix this issue (Karner's comment) ---> https://redcountyrp.com/forum/viewtopic.php?f=1566&t=138436

**Comment by reemyrobby** [comment]
The script already uses the enter point of a phone number when running a trace, but it can be inconsistent sometimes. ‎It is still working in-game, but there are times when it is still giving the incorrect information.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: DogNoSent: Thursday, January 26, 2017 7:00 AMTo: TommyB123/redcountyrp-bugsReply To: TommyB123/redcountyrp-bugsCc: SubscribedSubject: Re: [TommyB123/redcountyrp-bugs] /find gives you the wrong location if inside an interior (#65)There is one suggestion on the forums which if added will fix this issue (Karner's comment) ---> https://redcountyrp.com/forum/viewtopic.php?f=1566&t=138436

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TommyB123/redcountyrp-bugs","title":"TommyB123/redcountyrp-bugs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TommyB123/redcountyrp-bugs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DogNo in #65: There is one suggestion on the forums which if added will fix this issue (Karner's comment) ---\u003e https://redcountyrp.com/forum/viewtopic.php?f=1566\u0026t=138436"}],"action":{"name":"View Issue","url":"https://github.com/TommyB123/redcountyrp-bugs/issues/65#issuecomment-275260123"}}}

**Comment by TommyB123** [comment]
Fixed.
