### ISSUE TITLE
Paused nametag bug

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#75]
So for some people the nametag is bugging.
I was tabbed and a player said my nametag wasn't shwing the new [P].

And I noticed that someone is not tabbed, but was before, so the [P] stayed there, even if they weren't tabbing anymore.
![sa-mp-594](https://cloud.githubusercontent.com/assets/24966760/22378200/1521a920-e4b5-11e6-8d57-c1ec0a959c75.png)
![sa-mp-593](https://cloud.githubusercontent.com/assets/24966760/22378201/1521ae5c-e4b5-11e6-87f8-0fd3e8726980.png)

**Comment by TommyB123** [comment]
I only changed the message so I imagine it had something to do with the timer bug that fucked the entire server. See if it's working after the latest restart. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RAZR <notifications@github.com> Date: 1/27/17  10:22 AM  (GMT-06:00) To: TommyB123/redcountyrp-bugs <redcountyrp-bugs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [TommyB123/redcountyrp-bugs] Paused nametag bug (#75) 
So for some people the nametag is bugging.

I was tabbed and a player said my nametag wasn't shwing the new [P].
And I noticed that someone is not tabbed, but was before, so the [P] stayed there, even if they weren't tabbing anymore.





—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TommyB123/redcountyrp-bugs","title":"TommyB123/redcountyrp-bugs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TommyB123/redcountyrp-bugs"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Paused nametag bug (#75)"}],"action":{"name":"View Issue","url":"https://github.com/TommyB123/redcountyrp-bugs/issues/75"}}}

**Comment by wtfrazr** [comment]
I still seem to see it, just for a few seconds after the player came back from pausing. Maybe it's client side lag.

**Comment by TommyB123** [comment]
Yeah there's a slight bit of delay after a player comes back. Not really worth changing the code around imo.
